<a href="https://colab.research.google.com/github/JBawiskar/-Decision-Modeling-Practical/blob/main/Q_Learning_algorithm_EXP_3ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import gym

# Create the environment
env = gym.make('Taxi-v3')

# Initialize Q-table with zeros
Q = np.zeros([env.observation_space.n, env.action_space.n])

# Set hyperparameters
alpha = 0.1  # Learning rate
gamma = 0.6  # Discount factor
epsilon = 0.1  # Exploration rate

# Number of episodes
episodes = 1000

# Q-Learning algorithm
for _ in range(episodes):
    state = env.reset()
    done = False
    while not done:
        # Epsilon-greedy policy
        if np.random.uniform(0, 1) < epsilon:
            action = env.action_space.sample()  # Exploration
        else:
            action = np.argmax(Q[state])  # Exploitation

        next_state, reward, done, _ = env.step(action)

        # Q-value update
        old_q_value = Q[state, action]
        next_max = np.max(Q[next_state])
        new_q_value = (1 - alpha) * old_q_value + alpha * (reward + gamma * next_max)
        Q[state, action] = new_q_value

        state = next_state

# Print the learned Q-table
print("Learned Q-table:")
print(Q)

# Evaluate the learned policy
total_rewards = 0
episodes = 100
for _ in range(episodes):
    state = env.reset()
    done = False
    while not done:
        action = np.argmax(Q[state])
        state, reward, done, _ = env.step(action)
        total_rewards += reward

# Average reward over episodes
average_reward = total_rewards / episodes
print("Average Reward:", average_reward)


/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/utils/passive_env_checker.py:241: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


Learned Q-table:
[[ 0.          0.          0.          0.          0.          0.        ]
 [-2.31149458 -2.29169262 -2.2919748  -2.29230642 -2.28708674 -5.70211346]
 [-1.69451934 -1.64851202 -1.76998191 -1.66735897 -0.79519988 -4.92796951]
 ...
 [-1.1403963  -1.07257415 -1.13794621 -1.16538773 -1.96       -2.79623518]
 [-2.04744392 -2.03620388 -2.04925706 -2.05762856 -3.59811112 -3.71557856]
 [-0.1        -0.1        -0.1         1.74220941  0.          0.        ]]
Average Reward: -172.43
